/**
 * Raw Süper Lig 2026-27 roster data, transcribed from Transfermarkt club
 * pages on 13 August 2026.
 *
 * This is the SOURCE. `npm run build:squads` turns it into
 * lib/squad-packs.ts. Keeping the two apart means a squad refresh is a data
 * edit plus a regeneration, rather than hand-editing ~550 literal objects and
 * hoping the position counts still balance.
 *
 * IMPORTANT — what is and is not sourced:
 *   sourced   : name, shirt number, position, age, nationality
 *   estimated : ovr / pot
 *
 * Transfermarkt does not publish a single overall rating, so ovr/pot are
 * derived by lib/../scripts/build-squad-packs.ts from club tier, age and a
 * small hand-maintained table of well-known players. They are game-balance
 * numbers, not claims about real ability.
 *
 * CAVEAT: the 2026-27 Turkish transfer window opened 22 June and does not
 * close until 4 September 2026, so these rosters are a snapshot of a squad
 * list that is still moving. Re-run the fetch after the window shuts.
 *
 * Format per line: "number|Name|Transfermarkt position|age|nationality"
 * A number of "-" means Transfermarkt showed no shirt number.
 */

export type RawClub = {
  id: string;
  name: string;
  short: string;
  city: string;
  color: string;
  color2: string;
  /** Relative strength band; drives the base overall. */
  tier: 1 | 2 | 3 | 4 | 5;
  /** 1 = Süper Lig, 2 = 1. Lig (the division below). */
  division?: 1 | 2;
  /**
   * Empty for second-division clubs: the club identity is real (name, city,
   * colours, taken from the Transfermarkt 1. Lig table) but the squad is
   * generated at a lower strength band rather than transcribed. Second-tier
   * players are largely unrecognisable, and inventing a specific real
   * player-to-club mapping we cannot verify would be worse than an honestly
   * generated squad. Drop real rosters in here later and they take priority.
   */
  players: string[];
};

export const RAW_CLUBS: RawClub[] = [
  {
    id: "fb", name: "Fenerbahçe", short: "FB", city: "İstanbul",
    color: "#001a4b", color2: "#ffed00", tier: 1,
    players: [
      "31|Ederson|Goalkeeper|32|Brazil",
      "1|İrfan Can Eğribayat|Goalkeeper|28|Turkey",
      "34|Mert Günok|Goalkeeper|37|Turkey",
      "24|Jayden Oosterwolde|Centre-Back|25|Netherlands",
      "15|Nathan Aké|Centre-Back|31|Netherlands",
      "37|Milan Škriniar|Centre-Back|31|Slovakia",
      "4|Çağlar Söyüncü|Centre-Back|30|Turkey",
      "50|Rodrigo Becão|Centre-Back|30|Brazil",
      "14|Yiğit Efe Demir|Centre-Back|22|Turkey",
      "3|Archie Brown|Left-Back|24|England",
      "22|Levent Mercan|Left-Back|25|Turkey",
      "18|Mert Müldür|Right-Back|27|Turkey",
      "27|Nélson Semedo|Right-Back|32|Portugal",
      "5|İsmail Yüksek|Defensive Midfield|27|Turkey",
      "91|N'Golo Kanté|Defensive Midfield|35|France",
      "28|Bartuğ Elmaz|Defensive Midfield|23|Turkey",
      "6|Mattéo Guendouzi|Central Midfield|27|France",
      "7|Fred|Central Midfield|33|Brazil",
      "10|Marco Asensio|Attacking Midfield|30|Spain",
      "94|Talisca|Attacking Midfield|32|Brazil",
      "8|Mert Hakan Yandaş|Attacking Midfield|31|Turkey",
      "9|Kerem Aktürkoğlu|Left Winger|27|Turkey",
      "20|Anthony Musaba|Left Winger|25|Netherlands",
      "11|Mason Greenwood|Right Winger|24|England",
      "45|Dorgeles Nene|Right Winger|23|Mali",
      "23|Cengiz Ünder|Right Winger|29|Turkey",
      "17|İrfan Can Kahveci|Right Winger|31|Turkey",
      "-|Romelu Lukaku|Centre-Forward|33|Belgium",
      "19|Vedat Muriqi|Centre-Forward|32|Kosovo",
      "26|Sidiki Chérif|Centre-Forward|19|Guinea",
    ],
  },
  {
    id: "gs", name: "Galatasaray", short: "GS", city: "İstanbul",
    color: "#a90432", color2: "#fdb912", tier: 1,
    players: [
      "1|Uğurcan Çakır|Goalkeeper|30|Turkey",
      "19|Günay Güvenç|Goalkeeper|35|Turkey",
      "24|Jankat Yılmaz|Goalkeeper|21|Turkey",
      "6|Davinson Sánchez|Centre-Back|30|Colombia",
      "42|Abdülkerim Bardakcı|Centre-Back|31|Turkey",
      "-|Victor Nelsson|Centre-Back|27|Denmark",
      "23|Kaan Ayhan|Centre-Back|31|Turkey",
      "3|Metehan Baltacı|Centre-Back|23|Turkey",
      "91|Arda Ünyay|Centre-Back|19|Turkey",
      "4|Ismail Jakobs|Left-Back|26|Senegal",
      "17|Eren Elmalı|Left-Back|26|Turkey",
      "-|Wilfried Singo|Right-Back|25|Côte d'Ivoire",
      "7|Roland Sallai|Right-Back|29|Hungary",
      "12|Elias Jelert|Right-Back|23|Denmark",
      "18|Lesley Ugochukwu|Defensive Midfield|22|France",
      "34|Lucas Torreira|Defensive Midfield|30|Uruguay",
      "99|Mario Lemina|Defensive Midfield|32|Gabon",
      "5|Eyüp Aydın|Defensive Midfield|22|Turkey",
      "8|Gabriel Sara|Central Midfield|27|Brazil",
      "20|İlkay Gündoğan|Central Midfield|35|Germany",
      "74|Renato Nhaga|Central Midfield|19|Guinea-Bissau",
      "53|Siraçhan Nas|Attacking Midfield|24|Turkey",
      "76|Barış Alper Yılmaz|Left Winger|26|Turkey",
      "10|Leroy Sané|Right Winger|30|Germany",
      "11|Yunus Akgün|Right Winger|26|Turkey",
      "27|Armando Güner|Right Winger|18|Argentina",
      "-|Victor Osimhen|Centre-Forward|27|Nigeria",
      "-|Halil Dervişoğlu|Centre-Forward|26|Turkey",
      "124|Yalın Dilek|Centre-Forward|20|Turkey",
    ],
  },
  {
    id: "bjk", name: "Beşiktaş", short: "BJK", city: "İstanbul",
    color: "#111114", color2: "#f4f5f7", tier: 2,
    players: [
      "1|Alexander Nübel|Goalkeeper|29|Germany",
      "80|Doğan Alemdar|Goalkeeper|23|Turkey",
      "99|Emre Bilgin|Goalkeeper|22|Turkey",
      "12|Emmanuel Agbadou|Centre-Back|29|Côte d'Ivoire",
      "35|Tiago Djaló|Centre-Back|26|Portugal",
      "14|Felix Uduokhai|Centre-Back|28|Germany",
      "53|Emirhan Topçu|Centre-Back|25|Turkey",
      "58|Yasin Özcan|Centre-Back|20|Turkey",
      "-|Emrecan Uzunhan|Centre-Back|25|Turkey",
      "11|Kassoum Ouattara|Left-Back|21|France",
      "33|Rıdvan Yılmaz|Left-Back|25|Turkey",
      "62|Amir Murillo|Right-Back|30|Panama",
      "22|Taylan Bulut|Right-Back|20|Germany",
      "4|Wilfred Ndidi|Defensive Midfield|29|Nigeria",
      "-|Moatasem Al-Musrati|Defensive Midfield|30|Libya",
      "5|Amir Hadziahmetovic|Defensive Midfield|29|Bosnia-Herzegovina",
      "6|Salih Özcan|Defensive Midfield|28|Turkey",
      "8|Kartal Yılmaz|Defensive Midfield|25|Turkey",
      "10|Orkun Kökçü|Central Midfield|25|Turkey",
      "68|Fahri Ay|Central Midfield|21|Turkey",
      "15|Junior Olaitan|Attacking Midfield|24|Benin",
      "-|João Mário|Attacking Midfield|33|Portugal",
      "19|Leandro Trossard|Left Winger|31|Belgium",
      "29|İlhan Fakılı|Left Winger|20|Turkey",
      "18|Vaclav Cerny|Right Winger|28|Czech Republic",
      "7|Milot Rashica|Right Winger|30|Kosovo",
      "28|Dušan Vlahović|Centre-Forward|26|Serbia",
      "9|Oh Hyeon-gyu|Centre-Forward|25|South Korea",
      "90|Semih Kılıçsoy|Centre-Forward|20|Turkey",
      "23|Mustafa Hekimoğlu|Centre-Forward|19|Turkey",
    ],
  },
  {
    id: "ts", name: "Trabzonspor", short: "TS", city: "Trabzon",
    color: "#7a1b1f", color2: "#1e3a8a", tier: 2,
    players: [
      "24|André Onana|Goalkeeper|30|Cameroon",
      "25|Onuralp Çevikkan|Goalkeeper|20|Turkey",
      "1|Ahmet Yıldırım|Goalkeeper|19|Turkey",
      "44|Arseniy Batagov|Centre-Back|24|Ukraine",
      "27|Chibuike Nwaiwu|Centre-Back|23|Nigeria",
      "39|Cenk Özkacar|Centre-Back|25|Turkey",
      "4|Samet Akaydin|Centre-Back|32|Turkey",
      "15|Stefan Savic|Centre-Back|35|Montenegro",
      "55|Sidny Lopes Cabral|Left-Back|23|Cape Verde",
      "7|Mustafa Eskihellaç|Left-Back|29|Turkey",
      "20|Wagner Pina|Right-Back|23|Cape Verde",
      "-|Batista Mendy|Defensive Midfield|26|France",
      "-|John Lundstram|Defensive Midfield|32|England",
      "5|Okay Yokuşlu|Defensive Midfield|32|Turkey",
      "57|Melih Kabasakal|Defensive Midfield|30|Turkey",
      "26|Tim Jabol-Folcarelli|Central Midfield|26|France",
      "8|Benjamin Bouchouari|Central Midfield|24|Morocco",
      "17|Ruslan Malinovskyi|Central Midfield|33|Ukraine",
      "11|Ozan Tufam|Central Midfield|31|Turkey",
      "10|Ernest Muci|Attacking Midfield|25|Albania",
      "-|Göktan Gürpüz|Attacking Midfield|23|Turkey",
      "58|Aral Şimşir|Left Winger|24|Turkey",
      "70|Noah Saviolo|Left Winger|22|Portugal",
      "9|Metehan Mimaroğlu|Left Winger|32|Turkey",
      "77|Mohamed Salah|Right Winger|34|Egypt",
      "-|Cihan Çanak|Right Winger|21|Turkey",
      "30|Paul Onuachu|Centre-Forward|32|Nigeria",
      "-|Denis Drăguș|Centre-Forward|27|Romania",
      "19|René Mitongo|Centre-Forward|18|Belgium",
      "14|Umut Nayir|Centre-Forward|33|Turkey",
    ],
  },
  {
    id: "ibfk", name: "Başakşehir FK", short: "İBFK", city: "İstanbul",
    color: "#f97316", color2: "#1e3a8a", tier: 3,
    players: [
      "16|Muhammed Şengezer|Goalkeeper|29|Turkey",
      "1|Volkan Babacan|Goalkeeper|38|Turkey",
      "98|Deniz Dilmen|Goalkeeper|21|Turkey",
      "3|Jerome Opoku|Centre-Back|27|Ghana",
      "27|Ousseynou Ba|Centre-Back|30|Senegal",
      "23|Emin Bayram|Centre-Back|23|Turkey",
      "15|Hamza Güreler|Centre-Back|20|Turkey",
      "-|Francis Nzaba|Centre-Back|23|Congo",
      "21|Christopher Operi|Left-Back|29|Côte d'Ivoire",
      "33|Michal Karbownik|Left-Back|25|Poland",
      "6|Onur Bulut|Right-Back|32|Turkey",
      "42|Ömer Ali Şahiner|Right-Back|34|Turkey",
      "18|Jakub Kaluzinski|Defensive Midfield|23|Poland",
      "4|Onur Ergün|Defensive Midfield|33|Turkey",
      "20|Umut Güneş|Central Midfield|26|Turkey",
      "8|Olivier Kemen|Central Midfield|30|Cameroon",
      "-|Berkay Özcan|Central Midfield|28|Turkey",
      "17|Mohamed Hassan Fofana|Central Midfield|21|Côte d'Ivoire",
      "22|Ömer Beyaz|Attacking Midfield|22|Turkey",
      "77|Ivan Brnic|Left Winger|24|Croatia",
      "11|Abbosbek Fayzullaev|Right Winger|22|Uzbekistan",
      "70|Andreas Skov Olsen|Right Winger|26|Denmark",
      "34|Edin Visca|Right Winger|36|Bosnia-Herzegovina",
      "14|Eldor Shomurodov|Centre-Forward|31|Uzbekistan",
      "91|Bertuğ Yıldırım|Centre-Forward|24|Turkey",
      "-|Davie Selke|Centre-Forward|31|Germany",
      "9|Umut Bozok|Centre-Forward|29|Turkey",
    ],
  },
  {
    id: "sam", name: "Samsunspor", short: "SAM", city: "Samsun",
    color: "#dc2626", color2: "#ffffff", tier: 3,
    players: [
      "1|Okan Kocuk|Goalkeeper|31|Turkey",
      "-|Bilal Bayazıt|Goalkeeper|27|Turkey",
      "-|Efe Berat Töruz|Goalkeeper|19|Turkey",
      "-|Gabriele Guarino|Centre-Back|22|Italy",
      "-|Toni Borevković|Centre-Back|29|Croatia",
      "-|Igor Drapiński|Centre-Back|22|Poland",
      "-|Yunus Emre Çift|Centre-Back|22|Turkey",
      "-|Bedirhan Çetin|Centre-Back|20|Turkey",
      "-|Logi Tómasson|Left-Back|25|Iceland",
      "-|Enes Albak|Left-Back|21|Turkey",
      "-|Joe Mendes|Right-Back|23|Sweden",
      "-|Mustafa Tan|Right-Back|21|Turkey",
      "-|Antoine Makoumbou|Defensive Midfield|28|Congo",
      "-|Elliot Watt|Defensive Midfield|26|Scotland",
      "-|Antoine Sekongo|Central Midfield|22|Mali",
      "-|Yalçın Kayan|Central Midfield|27|Turkey",
      "-|Celil Yüksel|Central Midfield|28|Turkey",
      "-|Samed Onur|Central Midfield|24|Turkey",
      "-|Afonso Sousa|Attacking Midfield|26|Portugal",
      "-|Jaurès Assoumou|Left Winger|23|Côte d'Ivoire",
      "-|Emre Kılınç|Left Winger|31|Turkey",
      "-|Arbnor Muja|Right Winger|27|Albania",
      "-|Elayis Tavsan|Right Winger|25|Turkey",
      "-|Tanguy Coulibaly|Right Winger|25|France",
      "-|Marius Mouandilmadji|Centre-Forward|28|Chad",
      "-|Cherif Ndiaye|Centre-Forward|30|Senegal",
      "-|Fatih Kaya|Centre-Forward|26|Turkey",
      "-|Richie Omorowa|Centre-Forward|22|Sweden",
    ],
  },
  {
    id: "gzt", name: "Göztepe", short: "GZT", city: "İzmir",
    color: "#facc15", color2: "#dc2626", tier: 3,
    players: [
      "25|Luka Gugeshashvili|Goalkeeper|27|Georgia",
      "1|Arda Özçimen|Goalkeeper|24|Turkey",
      "33|Şamil Öztürk|Goalkeeper|21|Turkey",
      "26|Malcom Bokele|Centre-Back|26|Cameroon",
      "4|Taha Altıkardeş|Centre-Back|22|Turkey",
      "23|Furkan Bayır|Centre-Back|26|Turkey",
      "19|Noah Sonko Sundberg|Centre-Back|30|The Gambia",
      "3|Allan Godói|Centre-Back|33|Brazil",
      "13|Ege Yıldırım|Centre-Back|19|Turkey",
      "30|Anthony Dennis|Defensive Midfield|22|Nigeria",
      "20|Novatus Miroshi|Defensive Midfield|23|Tanzania",
      "-|Musah Mohammed|Defensive Midfield|24|Ghana",
      "-|Rhaldney|Central Midfield|27|Brazil",
      "6|Alex Matos|Central Midfield|21|England",
      "2|Arda Okan Kurtulan|Right Midfield|23|Turkey",
      "16|Ogün Bayrak|Right Midfield|27|Turkey",
      "15|Amin Cherni|Left Midfield|25|Tunisia",
      "8|Alexis Antunes|Attacking Midfield|26|Switzerland",
      "10|Efkan Bekiroğlu|Attacking Midfield|30|Turkey",
      "9|Juan|Centre-Forward|24|Brazil",
      "39|Janderson|Centre-Forward|27|Brazil",
      "7|André Henrique|Centre-Forward|24|Brazil",
      "22|Sinclair Armstrong|Centre-Forward|23|Ireland",
      "11|Guilherme Luiz|Centre-Forward|21|Brazil",
      "17|Gökdeniz Bayrakdar|Centre-Forward|24|Turkey",
    ],
  },
  {
    id: "riz", name: "Çaykur Rizespor", short: "RİZ", city: "Rize",
    color: "#16a34a", color2: "#1d4ed8", tier: 4,
    players: [
      "-|Yahia Fofana|Goalkeeper|25|Côte d'Ivoire",
      "-|Zafer Görgen|Goalkeeper|26|Turkey",
      "-|Efe Doğan|Goalkeeper|21|Turkey",
      "-|Siaka Bakayoko|Centre-Back|21|France",
      "-|Attila Mocsi|Centre-Back|26|Hungary",
      "-|Modibo Sagnan|Centre-Back|27|Mali",
      "-|Tayyip Talha Sanuç|Centre-Back|26|Turkey",
      "-|Khusniddin Alikulov|Centre-Back|27|Uzbekistan",
      "-|Hüseyincan Kırıkcı|Centre-Back|22|Turkey",
      "-|Zakaria Ariss|Left-Back|22|Morocco",
      "-|Umut Erdem|Left-Back|22|Turkey",
      "-|Taha Şahin|Right-Back|25|Turkey",
      "-|Mithat Pala|Right-Back|25|Turkey",
      "-|Taylan Antalyalı|Defensive Midfield|31|Turkey",
      "-|Qazim Laci|Central Midfield|30|Albania",
      "-|Ibrahim Olawoyin|Central Midfield|28|Nigeria",
      "-|Dal Varesanovic|Attacking Midfield|25|Bosnia-Herzegovina",
      "-|Eren Emre Aydın|Attacking Midfield|21|Turkey",
      "-|Valentin Mihăilă|Left Winger|26|Romania",
      "-|Ahmed Kutucu|Left Winger|26|Turkey",
      "-|Emrecan Bulut|Left Winger|23|Turkey",
      "-|Adedire Mebude|Right Winger|22|Scotland",
      "-|Mame Mor Faye|Right Winger|21|Senegal",
      "-|Ali Sowe|Centre-Forward|32|The Gambia",
    ],
  },
  {
    id: "aln", name: "Alanyaspor", short: "ALN", city: "Alanya",
    color: "#f97316", color2: "#16a34a", tier: 4,
    players: [
      "-|Yusuf Karagöz|Goalkeeper|26|Turkey",
      "-|Mert Bayram|Goalkeeper|21|Turkey",
      "-|Paulo Victor|Goalkeeper|39|Brazil",
      "-|Ümit Akdağ|Centre-Back|22|Romania",
      "-|Nuno Lima|Centre-Back|25|Portugal",
      "-|Fatih Aksoy|Centre-Back|28|Turkey",
      "-|Fidan Aliti|Centre-Back|32|Kosovo",
      "-|Bedirhan Özyurt|Centre-Back|23|Turkey",
      "-|Florent Hadergjonaj|Right-Back|32|Kosovo",
      "-|Enes Keskin|Right-Back|25|Turkey",
      "-|Yusuf Özdemir|Left-Back|25|Turkey",
      "-|Maestro|Defensive Midfield|23|Angola",
      "-|Gaius Makouta|Defensive Midfield|29|Congo",
      "-|Baran Gezek|Defensive Midfield|20|Turkey",
      "-|İzzet Çelik|Central Midfield|22|Turkey",
      "-|Emirhan Çavuş|Central Midfield|23|Turkey",
      "-|Ianis Hagi|Attacking Midfield|27|Romania",
      "-|İbrahim Kaya|Attacking Midfield|25|Turkey",
      "-|Ui-jo Hwang|Attacking Midfield|33|South Korea",
      "-|Ruan|Left Winger|21|Brazil",
      "-|Şahin Dik|Left Winger|22|Turkey",
      "-|Veysel Ünal|Right Winger|25|Turkey",
      "-|Batuhan Yavuz|Right Winger|21|Turkey",
      "-|Meschack Elia|Centre-Forward|29|DR Congo",
      "-|Omar Ben Ali|Centre-Forward|21|Tunisia",
    ],
  },
  {
    id: "kon", name: "Konyaspor", short: "KON", city: "Konya",
    color: "#16a34a", color2: "#ffffff", tier: 4,
    players: [
      "13|Bahadır Güngördü|Goalkeeper|30|Turkey",
      "1|Deniz Ertaş|Goalkeeper|21|Turkey",
      "29|Egemen Aydın|Goalkeeper|19|Turkey",
      "4|Adil Demirbağ|Centre-Back|28|Turkey",
      "15|Chidozie Awaziem|Centre-Back|29|Nigeria",
      "5|Uğurcan Yazğılı|Centre-Back|27|Turkey",
      "22|Rayyan Baniya|Centre-Back|27|Turkey",
      "37|Utku Eriş|Centre-Back|20|Turkey",
      "41|Da Mata|Centre-Back|20|Brazil",
      "3|Arthur Masuaku|Left-Back|32|DR Congo",
      "23|Arif Boşluk|Left-Back|23|Turkey",
      "8|Yhoan Andzouana|Right-Back|29|Congo",
      "77|Marko Jevtovic|Defensive Midfield|33|Serbia",
      "10|Melih İbrahimoğlu|Central Midfield|26|Turkey",
      "17|Enis Bardhi|Attacking Midfield|31|North Macedonia",
      "19|Diogo Gonçalves|Left Winger|29|Portugal",
      "45|Ebrima Colley|Left Winger|26|The Gambia",
      "9|Emir Bars|Left Winger|21|Turkey",
      "40|Deniz Türüç|Right Winger|33|Turkey",
      "99|Jackson Muleka|Centre-Forward|26|DR Congo",
      "113|Blaz Kramer|Centre-Forward|30|Slovenia",
    ],
  },
  {
    id: "ksm", name: "Kasımpaşa", short: "KSM", city: "İstanbul",
    color: "#1d4ed8", color2: "#ffffff", tier: 4,
    players: [
      "1|Andreas Gianniotis|Goalkeeper|33|Greece",
      "25|Ali Emre Yanar|Goalkeeper|28|Turkey",
      "89|Ramazan Özkanlı|Goalkeeper|23|Turkey",
      "4|Adem Arous|Centre-Back|22|Tunisia",
      "5|Matei Ilie|Centre-Back|23|Romania",
      "29|Taylan Aydın|Centre-Back|20|Turkey",
      "30|Ahmet Taha Dağbaşı|Centre-Back|21|Turkey",
      "-|Godfried Frimpong|Left-Back|27|Netherlands",
      "3|Jakob Jessen|Left-Back|22|Denmark",
      "2|Cláudio Winck|Right-Back|32|Brazil",
      "22|Kamil Ahmet Çörekçi|Right-Back|34|Turkey",
      "20|Ayberk Karapo|Right-Back|22|Turkey",
      "16|Andri Fannar Baldursson|Defensive Midfield|24|Iceland",
      "28|Elson Mendes|Defensive Midfield|20|Cape Verde",
      "27|Atakan Müjde|Defensive Midfield|22|Turkey",
      "26|Kerem Demirbay|Central Midfield|33|Germany",
      "10|Haris Hajradinovic|Attacking Midfield|32|Bosnia-Herzegovina",
      "12|Mortadha Ben Ouanes|Left Winger|32|Tunisia",
      "13|Thiemoko Diarra|Left Winger|23|Mali",
      "11|Ali Yavuz Kol|Left Winger|25|Turkey",
      "34|Fousseni Diabaté|Right Winger|30|Mali",
      "-|Mamadou Fall|Right Winger|34|Senegal",
      "9|Adrian Benedyczak|Centre-Forward|25|Poland",
      "19|Güven Yalçın|Centre-Forward|27|Turkey",
      "-|Yusuf Barası|Centre-Forward|23|Turkey",
    ],
  },
  {
    id: "gfk", name: "Gaziantep FK", short: "GFK", city: "Gaziantep",
    color: "#dc2626", color2: "#111114", tier: 4,
    players: [
      "1|Kacper Tobiasz|Goalkeeper|23|Poland",
      "-|İbrahim Kağan Alkış|Goalkeeper|20|Turkey",
      "-|Cemilhan Aslan|Goalkeeper|18|Turkey",
      "-|Arda Kızıldağ|Centre-Back|27|Turkey",
      "-|Myenty Abena|Centre-Back|31|Suriname",
      "-|Nazım Sangaré|Centre-Back|32|Turkey",
      "-|Florin Ștefan|Left-Back|30|Romania",
      "-|Kerim Calhanoglu|Left-Back|23|Germany",
      "-|Deian Sorescu|Right-Back|28|Romania",
      "-|Luis Pérez|Right-Back|31|Spain",
      "-|Sabahattin Destici|Right-Back|26|Turkey",
      "-|Ulrich Meleke|Defensive Midfield|27|Côte d'Ivoire",
      "-|Ogün Özçiçek|Defensive Midfield|27|Turkey",
      "-|Drissa Camara|Central Midfield|24|Côte d'Ivoire",
      "-|Juninho Bacuna|Central Midfield|29|Curaçao",
      "-|Karamba Gassama|Central Midfield|21|The Gambia",
      "-|Kacper Kozłowski|Attacking Midfield|22|Poland",
      "-|Victor Gidado|Attacking Midfield|22|Nigeria",
      "-|Alexandru Maxim|Attacking Midfield|36|Romania",
      "-|Mirza Cihan|Left Winger|25|Turkey",
      "-|Enver Kulasin|Right Winger|22|Bosnia-Herzegovina",
      "-|Ali Mevran Ablak|Right Winger|23|Turkey",
      "-|Trivante Stewart|Centre-Forward|26|Jamaica",
      "-|Serdar Dursun|Centre-Forward|34|Turkey",
      "-|Fuat Bavuk|Centre-Forward|26|Turkey",
    ],
  },
  {
    id: "koc", name: "Kocaelispor", short: "KOC", city: "Kocaeli",
    color: "#16a34a", color2: "#111114", tier: 4,
    players: [
      "-|Aleksandar Jovanovic|Goalkeeper|33|Serbia",
      "-|Onurcan Piri|Goalkeeper|31|Turkey",
      "-|Serhat Öztaşdelen|Goalkeeper|21|Turkey",
      "-|Anfernee Dijksteel|Centre-Back|29|Suriname",
      "-|Tanguy Zoukrou|Centre-Back|23|France",
      "-|Emir Ortakaya|Centre-Back|22|Turkey",
      "-|Onur Öztonga|Centre-Back|26|Turkey",
      "-|Mikdat Çil|Centre-Back|20|Turkey",
      "-|Massadio Haïdara|Left-Back|33|Mali",
      "-|Muharrem Cinan|Left-Back|28|Turkey",
      "-|Uğur Kaan Yıldız|Right-Back|24|Turkey",
      "-|Show|Defensive Midfield|27|Angola",
      "-|Mahamadou Susoho|Defensive Midfield|21|Spain",
      "-|Berkan Kutlu|Central Midfield|28|Turkey",
      "-|Habib Keïta|Central Midfield|24|Mali",
      "-|Tayfur Bingöl|Central Midfield|33|Turkey",
      "-|Samet Yalçın|Central Midfield|32|Turkey",
      "-|Rigoberto Rivas|Left Winger|28|Honduras",
      "-|Makana Baku|Left Winger|28|Germany",
      "-|Dan Agyei|Right Winger|29|Ghana",
      "-|Bedirhan Yıldız|Right Winger|21|Turkey",
      "-|Bruno Petkovic|Centre-Forward|31|Croatia",
      "-|Metehan Altunbaş|Centre-Forward|23|Turkey",
      "-|Arda Özyar|Centre-Forward|19|Turkey",
    ],
  },
  {
    id: "eyp", name: "Eyüpspor", short: "EYP", city: "İstanbul",
    color: "#7c3aed", color2: "#facc15", tier: 4,
    players: [
      "-|Horațiu Moldovan|Goalkeeper|28|Romania",
      "-|Umut Keseci|Goalkeeper|22|Turkey",
      "-|Jawad El Yamiq|Centre-Back|34|Morocco",
      "-|Anıl Yaşar|Centre-Back|24|Turkey",
      "-|Zak Jules|Centre-Back|29|Scotland",
      "-|Gilbert Mendy|Centre-Back|21|Senegal",
      "-|Berhan Kutlay Şatlı|Centre-Back|20|Turkey",
      "-|Arda Yavuz|Left-Back|20|Turkey",
      "-|Calegari|Right-Back|24|Brazil",
      "-|Talha Ülvan|Right-Back|25|Turkey",
      "-|Chandrel Massanga|Defensive Midfield|26|Congo",
      "-|Taşkın İlter|Defensive Midfield|32|Turkey",
      "-|Charles-André Raux-Yao|Central Midfield|24|France",
      "-|Hamza Akman|Central Midfield|21|Turkey",
      "-|Erdem Çalık|Central Midfield|20|Turkey",
      "-|Abdelhamid Sabiri|Attacking Midfield|29|Morocco",
      "-|David Costa|Attacking Midfield|22|Portugal",
      "-|Konrad Michalak|Left Winger|28|Poland",
      "-|Lenny Pintor|Left Winger|26|France",
      "-|Bilal Boutobba|Right Winger|27|France",
      "-|Mete Demir|Right Winger|28|Turkey",
      "-|Berkay Kumlu|Right Winger|21|Turkey",
      "-|Ahmed Abdullahi|Centre-Forward|22|Nigeria",
      "-|Abdou Khadre Sy|Centre-Forward|18|Senegal",
    ],
  },
  {
    id: "gbr", name: "Gençlerbirliği", short: "GBR", city: "Ankara",
    color: "#dc2626", color2: "#111114", tier: 4,
    players: [
      "-|Gökhan Akkan|Goalkeeper|31|Turkey",
      "-|Berk Deniz Çukurcu|Goalkeeper|18|Turkey",
      "-|Dimitrios Goutas|Centre-Back|32|Greece",
      "-|Thalisson|Centre-Back|28|Brazil",
      "-|Zan Zuzek|Centre-Back|29|Slovenia",
      "-|Ensar Çavuşoğlu|Centre-Back|24|Turkey",
      "-|Arda Çağan Çelik|Centre-Back|21|Turkey",
      "-|Kévin Rodrigues|Left-Back|32|Portugal",
      "-|Abdurrahim Dursun|Left-Back|27|Turkey",
      "-|Pedro Pereira|Right-Back|28|Portugal",
      "-|Fıratcan Üzüm|Right-Back|27|Turkey",
      "-|Berat Can Sebat|Right-Back|22|Turkey",
      "-|Moussa Kyabou|Defensive Midfield|28|Mali",
      "-|Peter Etebo|Defensive Midfield|30|Nigeria",
      "-|Ousmane Diabate|Defensive Midfield|18|Guinea",
      "-|Franco Tongya|Central Midfield|24|Italy",
      "-|Oğulcan Ülgün|Central Midfield|28|Turkey",
      "-|Ensar Kemaloğlu|Central Midfield|27|Turkey",
      "-|Göktuğ Erdem|Central Midfield|22|Turkey",
      "-|Adama Traoré|Right Winger|31|Mali",
      "-|Dilhan Demir|Right Winger|23|Germany",
      "-|Sékou Koïta|Centre-Forward|26|Mali",
      "-|Arda Akgül|Centre-Forward|21|Turkey",
    ],
  },
  {
    id: "cor", name: "Çorum FK", short: "COR", city: "Çorum",
    color: "#dc2626", color2: "#111114", tier: 4,
    players: [
      "-|Marcos Felipe|Goalkeeper|30|Brazil",
      "-|Erhan Erentürk|Goalkeeper|31|Turkey",
      "-|Arif Şimşir|Goalkeeper|21|Turkey",
      "-|Alexandre Penetra|Centre-Back|24|Portugal",
      "-|Hrvoje Smolcic|Centre-Back|25|Croatia",
      "-|Serdar Saatçı|Centre-Back|23|Turkey",
      "-|Arda Şengül|Centre-Back|27|Turkey",
      "-|Sinan Osmanoğlu|Centre-Back|36|Turkey",
      "-|Andrei Borza|Left-Back|20|Romania",
      "-|Cemali Sertel|Left-Back|26|Turkey",
      "-|Gökhan Sazdağı|Right-Back|31|Turkey",
      "-|Hüseyin Bulut|Right-Back|27|Turkey",
      "-|Berat Özdemir|Defensive Midfield|28|Turkey",
      "-|Ylber Ramadani|Defensive Midfield|30|Albania",
      "-|Mohamed Diomandé|Central Midfield|24|Côte d'Ivoire",
      "-|Markus Karlsbakk|Central Midfield|26|Norway",
      "-|Atakan Akkaynak|Central Midfield|27|Turkey",
      "-|Ahmed Ildız|Central Midfield|29|Turkey",
      "-|Kenan Fakılı|Attacking Midfield|23|Turkey",
      "-|Alexandros Kyziridis|Left Winger|25|Greece",
      "-|Emircan Gürlük|Left Winger|22|Turkey",
      "-|Burak Çoban|Left Winger|31|Turkey",
      "-|Hasan Abdulkareem|Right Winger|27|Iraq",
      "-|Semih Akyıldız|Right Winger|25|Turkey",
      "-|Jesús Ramírez|Centre-Forward|28|Venezuela",
      "-|Mame Thiam|Centre-Forward|33|Senegal",
    ],
  },
  {
    id: "amd", name: "Amed SK", short: "AMD", city: "Diyarbakır",
    color: "#16a34a", color2: "#dc2626", tier: 4,
    players: [
      "-|Alban Lafont|Goalkeeper|27|Côte d'Ivoire",
      "-|Burak Bozan|Goalkeeper|25|Turkey",
      "-|Abdulsamed Damlu|Goalkeeper|27|Turkey",
      "-|David Bates|Centre-Back|29|Scotland",
      "-|Lumbardh Dellova|Centre-Back|27|Kosovo",
      "-|Mehmet Yeşil|Centre-Back|28|Turkey",
      "-|Amadou Cissé|Centre-Back|20|Guinea",
      "-|Miraç Acer|Centre-Back|30|Turkey",
      "-|Kahraman Demirtaş|Centre-Back|32|Turkey",
      "-|Umut Meraş|Left-Back|30|Turkey",
      "-|Celal Hanalp|Right-Back|30|Turkey",
      "-|Emrullah Ertuş|Right-Back|25|Turkey",
      "-|Gökhan Gül|Defensive Midfield|28|Germany",
      "-|Rayan Raveloson|Defensive Midfield|29|Madagascar",
      "-|Cem Üstündag|Central Midfield|25|Austria",
      "-|Furkan Soyalp|Central Midfield|31|Turkey",
      "-|Rayan Lutin|Attacking Midfield|23|Comoros",
      "-|Dia Saba|Attacking Midfield|33|Israel",
      "-|Çekdar Orhan|Attacking Midfield|28|Turkey",
      "-|Yira Sor|Left Winger|26|Nigeria",
      "-|Ermal Krasniqi|Left Winger|27|Kosovo",
      "-|Mohamed Khalil|Left Winger|25|Syria",
      "-|Samuel Ballet|Right Winger|25|Switzerland",
      "-|Cıvan Süer|Right Winger|20|Turkey",
      "-|Gift Orban|Centre-Forward|24|Nigeria",
      "-|Mbaye Diagne|Centre-Forward|34|Senegal",
    ],
  },
  {
    id: "erz", name: "Erzurumspor FK", short: "ERZ", city: "Erzurum",
    color: "#1d4ed8", color2: "#ffffff", tier: 4,
    players: [
      "-|Matija Orbanic|Goalkeeper|26|Croatia",
      "-|Ertuğrul Taşkıran|Goalkeeper|36|Turkey",
      "-|Erkan Anapa|Goalkeeper|28|Turkey",
      "-|Yakup Kırtay|Centre-Back|23|Turkey",
      "-|Nihad Mujakic|Centre-Back|28|Bosnia-Herzegovina",
      "-|Amar Gerxhaliu|Centre-Back|24|Kosovo",
      "-|Emre Erdem|Centre-Back|24|Turkey",
      "-|Enes Yiğit|Centre-Back|23|Turkey",
      "-|Yiğit Baran Karaoğlan|Centre-Back|20|Turkey",
      "-|Guram Giorbelidze|Left-Back|30|Georgia",
      "-|Cengizhan Bayrak|Left-Back|26|Turkey",
      "-|Festy Ebosele|Right-Back|24|Ireland",
      "-|Orhan Ovacıklı|Right-Back|37|Turkey",
      "-|Brandon Baiye|Defensive Midfield|25|Belgium",
      "-|Sefa Akgün|Central Midfield|26|Turkey",
      "-|Murat Cem Akpınar|Central Midfield|27|Turkey",
      "-|Enes Karakaş|Central Midfield|23|Turkey",
      "-|Eren Özdemir|Central Midfield|23|Turkey",
      "-|Mert Önal|Central Midfield|22|Turkey",
      "-|Martín Rodríguez|Attacking Midfield|32|Chile",
      "-|Mustafa Fettahoğlu|Left Winger|25|Turkey",
      "-|Fernando Andrade|Left Winger|33|Brazil",
      "-|Gyrano Kerk|Right Winger|30|Suriname",
      "-|Nariman Akhundzada|Centre-Forward|22|Azerbaijan",
      "-|İlkan Sever|Centre-Forward|21|Turkey",
      "-|Eren Tozlu|Centre-Forward|35|Turkey",
    ],
  },
];

/**
 * TFF 1. Lig (second division) 2026-27, from the Transfermarkt league table
 * on 13 August 2026. Real club identities; squads generated by
 * scripts/build-squad-packs.ts at tier 5.
 *
 * The real division has 20 clubs. This uses 18 so both tiers run the same
 * 34-round calendar and roll their seasons together — a 20-club second
 * division would finish four days later than the top flight every year and
 * desynchronise promotion.
 */
export const RAW_DIVISION_2: RawClub[] = [
  { id: "brs", name: "Bursaspor", short: "BRS", city: "Bursa", color: "#16a34a", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "kay", name: "Kayserispor", short: "KAY", city: "Kayseri", color: "#facc15", color2: "#dc2626", tier: 5, division: 2, players: [] },
  { id: "ant", name: "Antalyaspor", short: "ANT", city: "Antalya", color: "#dc2626", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "svs", name: "Sivasspor", short: "SVS", city: "Sivas", color: "#dc2626", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "bdr", name: "Bodrum FK", short: "BDR", city: "Bodrum", color: "#16a34a", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "fkg", name: "Fatih Karagümrük", short: "FKG", city: "İstanbul", color: "#dc2626", color2: "#111114", tier: 5, division: 2, players: [] },
  { id: "pnd", name: "Pendikspor", short: "PND", city: "İstanbul", color: "#1d4ed8", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "bol", name: "Boluspor", short: "BOL", city: "Bolu", color: "#dc2626", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "umr", name: "Ümraniyespor", short: "ÜMR", city: "İstanbul", color: "#dc2626", color2: "#facc15", tier: 5, division: 2, players: [] },
  { id: "ist", name: "İstanbulspor", short: "İST", city: "İstanbul", color: "#facc15", color2: "#111114", tier: 5, division: 2, players: [] },
  { id: "sar", name: "Sarıyer", short: "SAR", city: "İstanbul", color: "#1d4ed8", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "man", name: "Manisa FK", short: "MAN", city: "Manisa", color: "#111114", color2: "#facc15", tier: 5, division: 2, players: [] },
  { id: "bnd", name: "Bandırmaspor", short: "BND", city: "Bandırma", color: "#dc2626", color2: "#111114", tier: 5, division: 2, players: [] },
  { id: "esr", name: "Esenler Erokspor", short: "ESR", city: "İstanbul", color: "#7c3aed", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "kec", name: "Keçiörengücü", short: "KEÇ", city: "Ankara", color: "#1d4ed8", color2: "#facc15", tier: 5, division: 2, players: [] },
  { id: "van", name: "Van Spor FK", short: "VAN", city: "Van", color: "#dc2626", color2: "#ffffff", tier: 5, division: 2, players: [] },
  { id: "igd", name: "Iğdır FK", short: "IĞD", city: "Iğdır", color: "#16a34a", color2: "#dc2626", tier: 5, division: 2, players: [] },
  { id: "mug", name: "Muğlaspor", short: "MUĞ", city: "Muğla", color: "#16a34a", color2: "#ffffff", tier: 5, division: 2, players: [] },
];
